###
POST   http://localhost:3000/file
Content-Type: application/json

{
   "userId":"6028dfd9dcd0c8335c7bc649",
   "folderId":"6028dfd9dcd0c8335c7bc649",
   "name":"hell0.pdf",
   "type":"pdf",
   "url":"req.body.url", 
   "filename":"req.body.filename"
   
}



//home 6028dfd9dcd0c8335c7bc64

//user 6028dfd9dcd0c8335c7bc647

###
DELETE http://localhost:3000/file/60290908971d4d304cacec8
###
Get http://localhost:3000/file/6028dfd9dcd0c8335c7bc648


